### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by udurraniAtPresage** [RightChain/gFirestoreR#1]
Thank you for creating this package. It seems to be very useful for R users like me. 

I've been trying to run the text example but can't figure out where to provide Firebase SDK service account key or API key. I'd really appreciate it if you please elaborate the set-up procedure.

**Comment by RightChain** [comment]
I based this package off of googleCloudStorageR, so you can follow [these instructions](https://cran.r-project.org/web/packages/googleCloudStorageR/vignettes/googleCloudStorageR.html) for setting up a service token with Google. You will then need to set values in your .Renviron file like this:
```
GFIRE_AUTH_FILE='location/of/the/service/token.json'
GFIRE_DEFAULT_PROJECT='name-of-your-project'
GFIRE_DEFAULT_DB='(default)'
```
The authentication should happen automatically. 


I would recommend you find a different package as I will not be supporting this one. It is not fully developed, and I have no plans to do so.

**Comment by udurraniAtPresage** [comment]
Thank you so much for your response. It is unfortunate that you won't be supporting this package, but I understand. Closing this issue now.

By the way, is there another R package you know of that interacts with firestore? I couldn't find any except yours.

**Comment by RightChain** [comment]
I couldn't find any either, which is why I started this package. While I was investigating using Firestore, I determined that a structured database like SQL would actually fit my needs better, so I stopped developing it. I ended up using a combination of SQL and cloud buckets where my SQL database held all the metadata, filenames, permissions, etc while the buckets held the actual data.

**Comment by udurraniAtPresage** [comment]
Thanks again.
